// <auto-generated />
using System;
using IsBasvuru.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsBasvuru.Persistence.Migrations
{
    [DbContext(typeof(IsBasvuruContext))]
    [Migration("20260103024717_IsDeneyimiNullableGuncelleme")]
    partial class IsDeneyimiNullableGuncelleme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IsBasvuru.Domain.Entities.AdminBilgileri.PanelKullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonGirisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("SubeId");

                    b.ToTable("PanelKullanicilari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.AdminBilgileri.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RolTanimi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Log.BasvuruIslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IslemAciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IslemTipi")
                        .HasColumnType("int");

                    b.Property<int>("MasterBasvuruId")
                        .HasColumnType("int");

                    b.Property<int>("PanelKullaniciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterBasvuruId");

                    b.HasIndex("PanelKullaniciId");

                    b.ToTable("BasvuruIslemLoglari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Log.CvDegisiklikLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DegisenAlanAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DegisenKayitId")
                        .HasColumnType("int");

                    b.Property<string>("DegisenTabloAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DegisiklikTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DegisiklikTipi")
                        .HasColumnType("int");

                    b.Property<string>("EskiDeger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MasterBasvuruId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("YeniDeger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MasterBasvuruId");

                    b.HasIndex("PersonelId");

                    b.ToTable("CvDegisiklikLoglari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.MasterBasvuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasvuruDurum")
                        .HasColumnType("int");

                    b.Property<int>("BasvuruOnayAsamasi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BasvuruVersiyonNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.ToTable("MasterBasvurular");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.BasvuruOnay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAdres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciCihaz")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KvkkId")
                        .HasColumnType("int");

                    b.Property<int>("OnayDurum")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KvkkId");

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.ToTable("BasvuruOnaylari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.BilgisayarBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Yetkinlik")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("BilgisayarBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.DigerKisiselBilgiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AskerlikDurumu")
                        .HasColumnType("int");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<int>("DavaDurumu")
                        .HasColumnType("int");

                    b.Property<string>("DavaNedeni")
                        .HasColumnType("longtext");

                    b.Property<int>("EhliyetDurumu")
                        .HasColumnType("int");

                    b.Property<int>("KaliciRahatsizlik")
                        .HasColumnType("int");

                    b.Property<string>("KaliciRahatsizlikAciklama")
                        .HasColumnType("longtext");

                    b.Property<int>("Kilo")
                        .HasColumnType("int");

                    b.Property<int>("KktcBelgeId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("SigaraKullanimi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KktcBelgeId");

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.ToTable("DigerKisiselBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.EgitimBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiplomaDurum")
                        .HasColumnType("int");

                    b.Property<int>("EgitimSeviyesi")
                        .HasColumnType("int");

                    b.Property<decimal?>("Gano")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("NotSistemi")
                        .HasColumnType("int");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("EgitimBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LojmanTalebiVarMi")
                        .HasColumnType("int");

                    b.Property<string>("NedenBiz")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.ToTable("IsBasvuruDetaylari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.IsDeneyimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AyrilisSebep")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Departman")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Pozisyon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SehirId")
                        .HasColumnType("int");

                    b.Property<string>("SirketAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ucret")
                        .HasColumnType("int");

                    b.Property<string>("UlkeAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SehirId");

                    b.HasIndex("UlkeId");

                    b.ToTable("IsDeneyimleri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.KisiselBilgiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<int>("CocukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("DogumIlceAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("DogumIlceId")
                        .HasColumnType("int");

                    b.Property<string>("DogumSehirAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("DogumSehirId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DogumUlkeAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("DogumUlkeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IkametgahIlceAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("IkametgahIlceId")
                        .HasColumnType("int");

                    b.Property<string>("IkametgahSehirAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("IkametgahSehirId")
                        .HasColumnType("int");

                    b.Property<string>("IkametgahUlkeAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("IkametgahUlkeId")
                        .HasColumnType("int");

                    b.Property<int>("MedeniDurum")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonWhatsapp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UyrukAdi")
                        .HasColumnType("longtext");

                    b.Property<int?>("UyrukId")
                        .HasColumnType("int");

                    b.Property<string>("VesikalikFotograf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DogumIlceId");

                    b.HasIndex("DogumSehirId");

                    b.HasIndex("DogumUlkeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IkametgahIlceId");

                    b.HasIndex("IkametgahSehirId");

                    b.HasIndex("IkametgahUlkeId");

                    b.HasIndex("PersonelId")
                        .IsUnique();

                    b.HasIndex("UyrukId");

                    b.ToTable("KisiselBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.ReferansBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalistigiKurum")
                        .HasColumnType("int");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IsYeri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("ReferansAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferansSoyadi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferansTelefon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("ReferansBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.SertifikaBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GecerlilikTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("SertifikaAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Suresi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("VerilisTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("SertifikaBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.YabanciDilBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DilId")
                        .HasColumnType("int");

                    b.Property<int>("DinlemeSeviyesi")
                        .HasColumnType("int");

                    b.Property<int>("KonusmaSeviyesi")
                        .HasColumnType("int");

                    b.Property<string>("NasilOgrenildi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OkumaSeviyesi")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("YazmaSeviyesi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("PersonelId");

                    b.ToTable("YabanciDilBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayAlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsBasvuruDetayId")
                        .HasColumnType("int");

                    b.Property<int>("SubeAlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsBasvuruDetayId");

                    b.HasIndex("SubeAlanId");

                    b.ToTable("IsBasvuruDetayAlanlari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayDepartman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<int>("IsBasvuruDetayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("IsBasvuruDetayId");

                    b.ToTable("IsBasvuruDetayDepartmanlari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayOyun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsBasvuruDetayId")
                        .HasColumnType("int");

                    b.Property<int>("OyunBilgisiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsBasvuruDetayId");

                    b.HasIndex("OyunBilgisiId");

                    b.ToTable("IsBasvuruDetayOyunlari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayPozisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmanPozisyonId")
                        .HasColumnType("int");

                    b.Property<int>("IsBasvuruDetayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanPozisyonId");

                    b.HasIndex("IsBasvuruDetayId");

                    b.ToTable("IsBasvuruDetayPozisyonlari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsBasvuruDetayId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramBilgisiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsBasvuruDetayId");

                    b.HasIndex("ProgramBilgisiId");

                    b.ToTable("IsBasvuruDetayProgramlari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetaySube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsBasvuruDetayId")
                        .HasColumnType("int");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsBasvuruDetayId");

                    b.HasIndex("SubeId");

                    b.ToTable("IsBasvuruDetaySubeler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.PersonelEhliyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EhliyetTuruId")
                        .HasColumnType("int");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EhliyetTuruId");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelEhliyetleri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DepartmanAktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubeAlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubeAlanId");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.DepartmanPozisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmanPozisyonAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DepartmanPozisyonAktifMi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("DepartmanPozisyonlar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.OyunBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OyunAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OyunBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.ProgramBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("ProgramBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubeAdi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("SubeAktifMi")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SubeAdi")
                        .IsUnique();

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.SubeAlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubeAlanAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SubeAlanAktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubeId");

                    b.ToTable("SubeAlanlar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Dil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DilAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Diller");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.EhliyetTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EhliyetTuruAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EhliyetTurleri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SehirId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.KktcBelge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BelgeAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KktcBelgeler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Kvkk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DogrulukAciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KvkkAciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KvkkVersiyon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferansAciklama")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kvkklar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UlkeId");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UlkeAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ulkeler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Uyruk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.Property<string>("UyrukAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UlkeId")
                        .IsUnique();

                    b.ToTable("Uyruklar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.AdminBilgileri.PanelKullanici", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId");

                    b.HasOne("IsBasvuru.Domain.Entities.AdminBilgileri.Rol", "Rol")
                        .WithMany("PanelKullanicilari")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Sube", "Sube")
                        .WithMany()
                        .HasForeignKey("SubeId");

                    b.Navigation("Departman");

                    b.Navigation("Rol");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Log.BasvuruIslemLog", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.MasterBasvuru", "MasterBasvuru")
                        .WithMany()
                        .HasForeignKey("MasterBasvuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.AdminBilgileri.PanelKullanici", "PanelKullanici")
                        .WithMany()
                        .HasForeignKey("PanelKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterBasvuru");

                    b.Navigation("PanelKullanici");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Log.CvDegisiklikLog", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.MasterBasvuru", "MasterBasvuru")
                        .WithMany()
                        .HasForeignKey("MasterBasvuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterBasvuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.MasterBasvuru", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.BasvuruOnay", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Kvkk", "Kvkk")
                        .WithMany()
                        .HasForeignKey("KvkkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithOne("BasvuruOnay")
                        .HasForeignKey("IsBasvuru.Domain.Entities.PersonelBilgileri.BasvuruOnay", "PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kvkk");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.BilgisayarBilgisi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("BilgisayarBilgileri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.DigerKisiselBilgiler", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.KktcBelge", "KktcBelge")
                        .WithMany()
                        .HasForeignKey("KktcBelgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithOne("DigerKisiselBilgiler")
                        .HasForeignKey("IsBasvuru.Domain.Entities.PersonelBilgileri.DigerKisiselBilgiler", "PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KktcBelge");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.EgitimBilgisi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("EgitimBilgileri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithOne("IsBasvuruDetay")
                        .HasForeignKey("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.IsDeneyimi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("IsDeneyimleri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId");

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeId");

                    b.Navigation("Personel");

                    b.Navigation("Sehir");

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.KisiselBilgiler", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ilce", "DogumIlce")
                        .WithMany()
                        .HasForeignKey("DogumIlceId");

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", "DogumSehir")
                        .WithMany()
                        .HasForeignKey("DogumSehirId");

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", "DogumUlke")
                        .WithMany()
                        .HasForeignKey("DogumUlkeId");

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ilce", "IkametgahIlce")
                        .WithMany()
                        .HasForeignKey("IkametgahIlceId");

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", "IkametgahSehir")
                        .WithMany()
                        .HasForeignKey("IkametgahSehirId");

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", "IkametgahUlke")
                        .WithMany()
                        .HasForeignKey("IkametgahUlkeId");

                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithOne("KisiselBilgiler")
                        .HasForeignKey("IsBasvuru.Domain.Entities.PersonelBilgileri.KisiselBilgiler", "PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Uyruk", "Uyruk")
                        .WithMany()
                        .HasForeignKey("UyrukId");

                    b.Navigation("DogumIlce");

                    b.Navigation("DogumSehir");

                    b.Navigation("DogumUlke");

                    b.Navigation("IkametgahIlce");

                    b.Navigation("IkametgahSehir");

                    b.Navigation("IkametgahUlke");

                    b.Navigation("Personel");

                    b.Navigation("Uyruk");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.ReferansBilgisi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("ReferansBilgileri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.SertifikaBilgisi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("SertifikaBilgileri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.YabanciDilBilgisi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("YabanciDilBilgileri")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayAlan", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "IsBasvuruDetay")
                        .WithMany("BasvuruAlanlar")
                        .HasForeignKey("IsBasvuruDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.SubeAlan", "SubeAlan")
                        .WithMany()
                        .HasForeignKey("SubeAlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsBasvuruDetay");

                    b.Navigation("SubeAlan");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayDepartman", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "IsBasvuruDetay")
                        .WithMany("BasvuruDepartmanlar")
                        .HasForeignKey("IsBasvuruDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");

                    b.Navigation("IsBasvuruDetay");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayOyun", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "IsBasvuruDetay")
                        .WithMany("BasvuruOyunlar")
                        .HasForeignKey("IsBasvuruDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.OyunBilgisi", "OyunBilgileri")
                        .WithMany()
                        .HasForeignKey("OyunBilgisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsBasvuruDetay");

                    b.Navigation("OyunBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayPozisyon", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.DepartmanPozisyon", "DepartmanPozisyon")
                        .WithMany()
                        .HasForeignKey("DepartmanPozisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "IsBasvuruDetay")
                        .WithMany("BasvuruPozisyonlar")
                        .HasForeignKey("IsBasvuruDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmanPozisyon");

                    b.Navigation("IsBasvuruDetay");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetayProgram", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "IsBasvuruDetay")
                        .WithMany("BasvuruProgramlar")
                        .HasForeignKey("IsBasvuruDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.ProgramBilgisi", "ProgramBilgisi")
                        .WithMany()
                        .HasForeignKey("ProgramBilgisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsBasvuruDetay");

                    b.Navigation("ProgramBilgisi");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.IsBasvuruDetaySube", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", "IsBasvuruDetay")
                        .WithMany("BasvuruSubeler")
                        .HasForeignKey("IsBasvuruDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Sube", "Sube")
                        .WithMany()
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IsBasvuruDetay");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.PersonelEhliyet", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.EhliyetTuru", "EhliyetTuru")
                        .WithMany("PersonelEhliyetler")
                        .HasForeignKey("EhliyetTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvuru.Domain.Entities.Personel", "Personel")
                        .WithMany("PersonelEhliyetler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EhliyetTuru");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.SubeAlan", "SubeAlan")
                        .WithMany("Departmanlar")
                        .HasForeignKey("SubeAlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubeAlan");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.DepartmanPozisyon", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", "Departman")
                        .WithMany("DepartmanPozisyonlar")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.ProgramBilgisi", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", "Departman")
                        .WithMany()
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.SubeAlan", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Sube", "Sube")
                        .WithMany("SubeAlanlar")
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Ilce", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", "Sehir")
                        .WithMany("Ilceler")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", "Ulke")
                        .WithMany("Sehirler")
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Uyruk", b =>
                {
                    b.HasOne("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", "Ulke")
                        .WithOne("Uyruk")
                        .HasForeignKey("IsBasvuru.Domain.Entities.Tanimlamalar.Uyruk", "UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.AdminBilgileri.Rol", b =>
                {
                    b.Navigation("PanelKullanicilari");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Personel", b =>
                {
                    b.Navigation("BasvuruOnay")
                        .IsRequired();

                    b.Navigation("BilgisayarBilgileri");

                    b.Navigation("DigerKisiselBilgiler")
                        .IsRequired();

                    b.Navigation("EgitimBilgileri");

                    b.Navigation("IsBasvuruDetay")
                        .IsRequired();

                    b.Navigation("IsDeneyimleri");

                    b.Navigation("KisiselBilgiler")
                        .IsRequired();

                    b.Navigation("PersonelEhliyetler");

                    b.Navigation("ReferansBilgileri");

                    b.Navigation("SertifikaBilgileri");

                    b.Navigation("YabanciDilBilgileri");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.PersonelBilgileri.IsBasvuruDetay", b =>
                {
                    b.Navigation("BasvuruAlanlar");

                    b.Navigation("BasvuruDepartmanlar");

                    b.Navigation("BasvuruOyunlar");

                    b.Navigation("BasvuruPozisyonlar");

                    b.Navigation("BasvuruProgramlar");

                    b.Navigation("BasvuruSubeler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Departman", b =>
                {
                    b.Navigation("DepartmanPozisyonlar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.Sube", b =>
                {
                    b.Navigation("SubeAlanlar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.SirketYapisi.SirketTanimYapisi.SubeAlan", b =>
                {
                    b.Navigation("Departmanlar");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.EhliyetTuru", b =>
                {
                    b.Navigation("PersonelEhliyetler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Sehir", b =>
                {
                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("IsBasvuru.Domain.Entities.Tanimlamalar.Ulke", b =>
                {
                    b.Navigation("Sehirler");

                    b.Navigation("Uyruk");
                });
#pragma warning restore 612, 618
        }
    }
}
